import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../app/router/route_names.dart';
import '../../../../app/theme/colors.dart';
import '../../../../core/utils/formatters.dart';
import '../controllers/vouchers_controller.dart';

class VouchersScreen extends ConsumerWidget {
  const VouchersScreen({super.key});

  static const routeName = RouteNames.vouchers;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final vouchersAsync = ref.watch(vouchersProvider);

    return Scaffold(
      backgroundColor: const Color(0xFFFAFAFA),
      appBar: AppBar(
        title: const Text('Mã giảm giá'),
        elevation: 0,
        backgroundColor: Colors.white,
        foregroundColor: AppColors.ink,
      ),
      body: vouchersAsync.when(
        loading: () => const Center(child: CircularProgressIndicator(color: AppColors.forest)),
        error: (error, _) => Center(
          child: Text('Đã xảy ra lỗi: ${error.toString()}', style: const TextStyle(color: AppColors.danger)),
        ),
        data: (vouchers) {
          if (vouchers.isEmpty) {
            return const _EmptyVouchersContent();
          }

          return ListView.separated(
            padding: const EdgeInsets.all(20),
            itemCount: vouchers.length,
            separatorBuilder: (_, _) => const SizedBox(height: 16),
            itemBuilder: (context, index) {
              final voucher = vouchers[index];
              return _VoucherCard(voucher: voucher);
            },
          );
        },
      ),
    );
  }
}

class _VoucherCard extends StatelessWidget {
  const _VoucherCard({required this.voucher});

  final dynamic voucher; // Voucher class generated by drift

  @override
  Widget build(BuildContext context) {
    final discountText = voucher.discountPercent == 100
        ? 'FREESHIP'
        : '-${voucher.discountPercent}%';
    
    final formattedMaxDiscount = MoneyFormatter.vndFromLegacy(
      voucher.maxDiscount,
    );
    final maxDiscountText = voucher.discountPercent == 100
        ? 'Tối đa $formattedMaxDiscount'
        : 'Giảm tối đa $formattedMaxDiscount';

    return Container(
      height: 104,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: Row(
          children: [
            // Left portion: discount badge
            Container(
              width: 104,
              height: double.infinity,
              color: AppColors.forest,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.confirmation_num_outlined, color: Colors.white, size: 24),
                  const SizedBox(height: 6),
                  Text(
                    discountText,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                ],
              ),
            ),

            // Dashed separator line
            const _DashedLineSeparator(),

            // Right portion: voucher details
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      voucher.voucherName,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: const TextStyle(
                        color: AppColors.ink,
                        fontSize: 16,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'Đơn tối thiểu ${MoneyFormatter.vndFromLegacy(voucher.minOrderValue)} • $maxDiscountText',
                      style: const TextStyle(
                        color: AppColors.muted,
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const Spacer(),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.honey.withValues(alpha: 0.12),
                            borderRadius: BorderRadius.circular(6),
                          ),
                          child: Text(
                            voucher.code,
                            style: const TextStyle(
                              color: AppColors.coffee,
                              fontSize: 12,
                              fontWeight: FontWeight.w800,
                              letterSpacing: 1.1,
                            ),
                          ),
                        ),
                        InkWell(
                          onTap: () {
                            Clipboard.setData(ClipboardData(text: voucher.code));
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text('Đã sao chép mã "${voucher.code}" vào bộ nhớ tạm'),
                                duration: const Duration(seconds: 2),
                              ),
                            );
                          },
                          borderRadius: BorderRadius.circular(8),
                          child: const Padding(
                            padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            child: Text(
                              'Lấy mã',
                              style: TextStyle(
                                color: AppColors.forest,
                                fontSize: 13,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _DashedLineSeparator extends StatelessWidget {
  const _DashedLineSeparator();

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 1,
      height: double.infinity,
      child: LayoutBuilder(
        builder: (context, constraints) {
          final boxHeight = constraints.constrainHeight();
          const dashHeight = 5.0;
          const dashGap = 3.0;
          final dashCount = (boxHeight / (dashHeight + dashGap)).floor();
          return Flex(
            direction: Axis.vertical,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: List.generate(dashCount, (_) {
              return const SizedBox(
                width: 1,
                height: dashHeight,
                child: DecoratedBox(
                  decoration: BoxDecoration(color: Color(0xFFE2E4E2)),
                ),
              );
            }),
          );
        },
      ),
    );
  }
}

class _EmptyVouchersContent extends StatelessWidget {
  const _EmptyVouchersContent();

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(40),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 120,
              height: 120,
              decoration: BoxDecoration(
                color: AppColors.mist,
                borderRadius: BorderRadius.circular(60),
              ),
              child: const Icon(
                Icons.confirmation_num_outlined,
                size: 60,
                color: AppColors.muted,
              ),
            ),
            const SizedBox(height: 24),
            const Text(
              'Không có mã giảm giá',
              style: TextStyle(
                fontSize: 22,
                fontWeight: FontWeight.w800,
                color: AppColors.ink,
              ),
            ),
            const SizedBox(height: 12),
            const Text(
              'Hiện tại không có chương trình khuyến mãi nào hoạt động. Quay lại sau nhé!',
              style: TextStyle(
                fontSize: 15,
                color: AppColors.muted,
              ),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}
